export const userData = [
  {
    name: "Jan",
    "active user": 8690,
  },
  {
    name: "Feb",
    "active user": 3990,
  },
  {
    name: "March",
    "active user": 6890,
  },
  {
    name: "Apr",
    "active user": 4890,
  },
  {
    name: "May",
    "active user": 10690,
  },
  {
    name: "Jun",
    "active user": 12990,
  },
  {
    name: "July",
    "active user": 7890,
  },
  {
    name: "Aug",
    "active user": 4890,
  },
  {
    name: "Sep",
    "active user": 18690,
  },
  {
    name: "Oct",
    "active user": 3090,
  },
  {
    name: "Nov",
    "active user": 6890,
  },
  {
    name: "Dec",
    "active user": 4890,
  },
];
export const rows = [
  {
    id: 1,
    lastName: "Snow",
    firstName: "Jon",
    email: "jon@gmail.com",
    status: "active",
    avatar: "https://i.ibb.co/f0kK5w2/IMG-20201121-232938-removebg-preview.png",
    transactions: "$120.30",
  },
  {
    id: 2,
    lastName: "Snow",
    firstName: "Jon",
    email: "jon@gmail.com",
    status: "active",
    avatar: "https://i.ibb.co/f0kK5w2/IMG-20201121-232938-removebg-preview.png",
    transactions: "$120.30",
  },
  {
    id: 3,
    lastName: "Snow",
    firstName: "Jon",
    email: "jon@gmail.com",
    status: "active",
    avatar: "https://i.ibb.co/f0kK5w2/IMG-20201121-232938-removebg-preview.png",
    transactions: "$120.30",
  },
  {
    id: 4,
    lastName: "Snow",
    firstName: "Jon",
    email: "jon@gmail.com",
    status: "active",
    avatar: "https://i.ibb.co/f0kK5w2/IMG-20201121-232938-removebg-preview.png",
    transactions: "$120.30",
  },
  {
    id: 5,
    lastName: "Snow",
    firstName: "Jon",
    email: "jon@gmail.com",
    status: "active",
    avatar: "https://i.ibb.co/f0kK5w2/IMG-20201121-232938-removebg-preview.png",
    transactions: "$120.30",
  },
  {
    id: 6,
    lastName: "Snow",
    firstName: "Jon",
    email: "jon@gmail.com",
    status: "active",
    avatar: "https://i.ibb.co/f0kK5w2/IMG-20201121-232938-removebg-preview.png",
    transactions: "$120.30",
  },
  {
    id: 7,
    lastName: "Snow",
    firstName: "Jon",
    email: "jon@gmail.com",
    status: "active",
    avatar: "https://i.ibb.co/f0kK5w2/IMG-20201121-232938-removebg-preview.png",
    transactions: "$120.30",
  },
  {
    id: 8,
    lastName: "Snow",
    firstName: "Jon",
    email: "jon@gmail.com",
    status: "active",
    avatar: "https://i.ibb.co/f0kK5w2/IMG-20201121-232938-removebg-preview.png",
    transactions: "$120.30",
  },
  {
    id: 9,
    lastName: "Snow",
    firstName: "Jon",
    email: "jon@gmail.com",
    status: "active",

    avatar: "https://i.ibb.co/f0kK5w2/IMG-20201121-232938-removebg-preview.png",
    transactions: "$120.30",
  },
  {
    id: 10,
    lastName: "Snow",
    firstName: "Jon",
    email: "jon@gmail.com",
    status: "active",
    avatar: "https://i.ibb.co/f0kK5w2/IMG-20201121-232938-removebg-preview.png",
    transactions: "$120.30",
  },
];
